---
fb_api_token: "{{ lookup('ansible.builtin.env', 'PUREFB_API') }}"
fb_server_name: "server"
fb_dns_name: "dns"
fb_interface_name: "interface"
fb_export_policy_name: "export-policy"
fb_export_policy_tls_name: "export-policy-tls"
fb_s3_account_name: "cosi-account"
fb_s3_export_policy_name: "_s3_export_allow_everything"
fb_admin_policy_name: "realm-admin-policy"
fb_admin_user: "realm-admin"
fb_cert_name: "realm-cert"
fb_tls_policy_name: "tls-policy"
fb_validate_certs: true
fb_subnet_mtu: 9000
fb_subnet_lag: "uplink"
aws_region: "us-east-1"
aws_profile: "{{ lookup('ansible.builtin.env', 'AWS_PROFILE') | default('default', true) }}"
