apiVersion: v1
kind: Secret
metadata:
  name: px-pure-secret # must be this specific name
  namespace: portworx
type: Opaque
stringData:
  pure.json: |
    {
      "FlashBlades": [
        {
          "MgmtEndPoint": "10.3.11.50",
          "APIToken": "<your-token>", # Use the API token generated for the realm user.
          "Realm": "<realm-name>",
          "NFSEndPoint": "<nfs-endpoint>"
        }
      ]
    }
