allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pure-fb-nfsv4
mountOptions:
- nfsvers=4.1
- tcp
parameters:
  backend: pure_file
  pure_nfs_policy: 'export-policy' # name of the policy in the realm. If one doesn't exist, it will be created
  pure_nfs_server: "nfs-server" # must specify this to match the name of server in realm
  pure_fb_hard_limit_enabled:  "true"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
